### ISSUE TITLE
poorly made

### ISSUE THREAD

**Issue by accusable** [jgord559/Discord-Account-Creator#1]
I looked at your code, it is poorly made and could be heavily improved also use 
```py
with requests.Session() as session:
 ses = session.get('url')```

**Comment by jgord559** [comment]
Honestly could not care less

**Comment by accusable** [comment]
> Honestly could not care less

add me on discord blog#8751 we talked awhile ago when you needed help getting tiktok api my name is zt.

**Comment by accusable** [comment]
> > Honestly could not care less
> 
> add me on discord blog#8751 we talked awhile ago when you needed help w a project my name is zt.
